[workspace]
resolver = "3"

members = [
  "crates/*",
]

[workspace.package]
version = "1.0.0"
authors = ["miden contributors"]
description = "Diagnostics infrastructure for Miden tooling"
repository = "https://github.com/0xMiden/miden-diagnostics"
homepage = "https://github.com/0xMiden/miden-diagnostics"
documentation = "https://github.com/0xMiden/miden-diagnostics"
categories = ["Compilers"]
keywords = ["compiler", "miden"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.97"
exclude = [".github/", "docs/", "experiments/"]

[profile.release]
opt-level = 2
lto = true
